# Generated by Django 5.2.8 on 2025-11-15 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created='now')),
                ('title', models.CharField(max_length=122)),
                ('description', models.TextField(null=True)),
            ],
        ),
    ]
